spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8070
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8072

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"
