global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: test1-config
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['configserver:8070']
  - job_name: eureka-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eurekaserver:8090']
  - job_name: test1
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['test1:8080']
  - job_name: test2
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['test2:8081']
  - job_name: gatewayserver
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gatewayserver:8060']